// Generated by CoffeeScript 1.12.1
(function() {
  var RootRouter;

  RootRouter = (function() {
    function RootRouter(ioc) {
      if (ioc.RootRouter == null) {
        ioc.RootRouter = RootRouter;
      }
    }

    RootRouter.prototype.indexGet = function(req, res) {
      return res.render('index.pug');
    };

    RootRouter.prototype.setup = function(app) {
      return app.get('/', this.indexGet);
    };

    return RootRouter;

  })();

  module.exports = RootRouter;

}).call(this);
