// Generated by CoffeeScript 1.12.1
(function() {
  var StaticMock;

  StaticMock = (function() {
    function StaticMock(path) {
      this.path = path;
      ({});
    }

    return StaticMock;

  })();

  module.exports = StaticMock;

}).call(this);
